style"gtktreeviewheader"{
xthickness=0
ythickness=2
GtkButton::inner-border={4,4,1,4}
bg[NORMAL]=@base_color
bg[SELECTED]=@selected_base_color
bg[PRELIGHT]=@base_color
bg[ACTIVE]=@selected_base_color
bg[INSENSITIVE]=@base_color
engine"pixmap"{
image{
function=SHADOW
file="../images/gtk-2.0/header-shadow.svg"
border={0,1,0,1}
stretch=TRUE}}}
widget_class"*.<GtkTreeView>.<GtkButton>"style"gtktreeviewheader"
widget_class"*.<GtkCTree>.<GtkButton>"style"gtktreeviewheader"
widget_class"*.<GtkList>.<GtkButton>"style"gtktreeviewheader"
widget_class"*.<GtkCList>.<GtkButton>"style"gtktreeviewheader"
