[Icon Theme]
Name=phlat
Comment=Simple HighContrast theme
Example=face-wink
Inherits=hicolor

Directories=symbolic,symbolic-22,symbolic-24,symbolic-32,emblems,emblems-24

[symbolic]
Size=16
Context=Actions
Type=Scalable
MinSize=8
MaxSize=20

[symbolic]
Size=16
Context=Applications
Type=Scalable
MinSize=8
MaxSize=20

[symbolic]
Size=16
Context=MimeTypes
Type=Scalable
MinSize=8
MaxSize=20

[symbolic]
Size=16
Context=Devices
Type=Scalable
MinSize=8
MaxSize=20

[symbolic]
Size=16
Context=Emotes
Type=Scalable
MinSize=8
MaxSize=20

[symbolic]
Size=16
Context=FileSystems
Type=Scalable
MinSize=8
MaxSize=20

[symbolic]
Size=16
Context=Places
Type=Scalable
MinSize=8
MaxSize=20

[symbolic]
Size=16
Context=Categories
Type=Scalable
MinSize=8
MaxSize=20

[symbolic]
Size=16
Context=Status
Type=Scalable
MinSize=8
MaxSize=20

[symbolic]
Size=16
Context=Stock
Type=Scalable
MinSize=8
MaxSize=20

[symbolic-22]
Size=22
Context=Actions
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-22]
Size=22
Context=Applications
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-22]
Size=22
Context=MimeTypes
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-22]
Size=22
Context=Devices
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-22]
Size=22
Context=Emotes
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-22]
Size=22
Context=FileSystems
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-22]
Size=22
Context=Places
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-22]
Size=22
Context=Categories
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-22]
Size=22
Context=Status
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-22]
Size=22
Context=Stock
Type=Scalable
MinSize=21
MaxSize=23

[symbolic-32]
Size=32
Context=Actions
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-32]
Size=32
Context=Applications
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-32]
Size=32
Context=MimeTypes
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-32]
Size=32
Context=Devices
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-32]
Size=32
Context=Emotes
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-32]
Size=32
Context=FileSystems
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-32]
Size=32
Context=Places
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-32]
Size=32
Context=Categories
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-32]
Size=32
Context=Status
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-32]
Size=32
Context=Stock
Type=Scalable
MinSize=30
MaxSize=42

[symbolic-24]
Size=24
Context=Actions
Type=Scalable

[symbolic-24]
Size=24
Context=Applications
Type=Scalable

[symbolic-24]
Size=24
Context=MimeTypes
Type=Scalable

[symbolic-24]
Size=24
Context=Devices
Type=Scalable

[symbolic-24]
Size=24
MaxSize=256
Context=Emotes
Type=Scalable

[symbolic-24]
Size=24
Context=FileSystems
Type=Scalable

[symbolic-24]
Size=24
Context=Places
Type=Scalable

[symbolic-24]
Size=24
Context=Categories
Type=Scalable

[symbolic-24]
Size=24
Context=Status
Type=Scalable

[symbolic-24]
Size=24
Context=Stock
Type=Scalable

##Emblems

[emblems]
Size=16
Context=Emblems
Type=Scalable

[emblems-24]
Size=24
Context=Emblems
Type=Scalable
