#!/bin/bash

#    al-polybar-pipemenu - an Openbox pipemenu for polybar manipulation
#    .
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

HELP='    al-polybar-pipemenu an Openbox Pipe Menu for Polybar
    It should normally be called from an openbox menu.
Options:
    -h --help   show this message
    If al-polybar-pipemenu is called with no options (the usual method),
    it will output an xml openbox pipemenu for handling polybar sessions,
    and editing configuration files.
For more information, see "man polybar"
and "Help">"Polybar" in the ArchLabs menu.
'
# look for a help option somewhere
for i in "$@"
do
    case "$i" in
    -h|--help)
        echo "$HELP"
        exit 0
        ;;
    esac
done

AL_COMMON_LIBDIR='/usr/lib/archlabs/common'

CONFIGPATH="$HOME/.config/polybar"
CONFIG="$CONFIGPATH/config"

if ! . "$AL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
    echo $"Error: Failed to source al-include.cfg in $AL_COMMON_LIBDIR" >&2
    exit 1
fi

loadTEditmenu(){
    menuSeparator
    menuItem "Main config" "exo-open $CONFIG"
    if [ "$(pidof polybar)" ];then
        menuSubmenu "RunningBar" "Running Bars"
        pgrep -a polybar | while read -r pid cmd; do
            if [[ ${cmd%% *} = polybar ]]; then
                CONF=${cmd##* }
                CONFIG=${HOME}/.config/polybar/config
                if [[ $CONF = polybar ]];then
                    CONF="$CONFIG"
                    CONFIG="Main config"
                fi
                menuItem "$CONF Config" "exo-open $CONFIG"
            fi
        done
        menuSubmenuEnd
    fi
}

getConfigs(){
    menuSubmenu "EditConfigs" "Edit Configs"
        if type al-polybar-edit &>/dev/null;then  # al-polybar-edit script found
            menuItem "Edit Polybar Configs" "al-polybar-edit"
            loadTEditmenu
        else
            loadTEditmenu
        fi
    menuSubmenuEnd
}

loadLaunchmenu(){
    if [ "$(pidof polybar)" ];then
        if type $CONFIGPATH/scripts/launch.sh &>/dev/null;then  # launch script found
            menuItem "Start/Reload Polybar" "$CONFIGPATH/scripts/launch.sh"
        fi
    fi
}

loadKillmenu(){
    if [ "$(pidof polybar)" ];then
        if type $CONFIGPATH/scripts/killbar &>/dev/null;then  # launch script found
            menuItem "Stop Polybar" "$CONFIGPATH/scripts/killbar"
        fi
    fi
}

menuStart "Polybarmenu" "Polybar"
loadLaunchmenu
loadKillmenu
getConfigs
menuEnd
