style"gtktreeviewheader"{
xthickness=0
ythickness=4
GtkButton::inner-border={8,8,2,8}
bg[NORMAL]=@base_color
bg[SELECTED]=@selected_base_color
bg[PRELIGHT]=@base_color
bg[ACTIVE]=@selected_base_color
bg[INSENSITIVE]=@base_color
engine"pixmap"{
image{
function=SHADOW
file="../images/gtk-2.0/header-shadow.svg"
border={0,2,0,2}
stretch=TRUE}}}
widget_class"*.<GtkTreeView>.<GtkButton>"style"gtktreeviewheader"
widget_class"*.<GtkCTree>.<GtkButton>"style"gtktreeviewheader"
widget_class"*.<GtkList>.<GtkButton>"style"gtktreeviewheader"
widget_class"*.<GtkCList>.<GtkButton>"style"gtktreeviewheader"
