#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         6
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle  	 true
bspc config gapless_monocle     	 true
bspc config focus_follows_pointer	 true
bspc config click_to_focus		 true
bspc config top_padding 54
bspc rule -a \* node=focused split_dir=east
bspc config focused_border_color    '#f0f0f0'
bspc config center_pseudo_tiled 	false
bspc config single_monocle 		true

feh --bg-fill /home/markus/Pictures/city_2.jpeg &
compton &
xsetroot -cursor_name left_ptr &
polybar top &
xsetroot -cursor_name left_ptr &
xrandr --dpi 188 &
export GDK_SCALE=2 &
export GDK_DPI_SCALE=0.4 &
